#!/bin/bash

# auxiliary function to convert a path to the current os
__normalizeOsPath() {
  if [[ "$BSYS_OS" == "windows" ]]; then
    echo $(cygpath -w "$1" | tr '\\' '/')
  # posix
  else
    echo "$1"
  fi
}

# showing help
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "$(basename "$0") [-h] -- Runs the installation:
    -h/--help      show this help text
    --production   installs as production release (under BACKBONE_ROOT). Otherwise, if not supplied installs under BACKBONE_DEV_ROOT (default)"
  exit 0
fi

# reading info.json
name=$(grep -Po "\"name\": *\K\"[^\"]*\"" info.json | cut -d '"' -f 2)
type=$(grep -Po "\"type\": *\K\"[^\"]*\"" info.json | cut -d '"' -f 2)
version=$(grep -Po "\"version\": *\K\"[^\"]*\"" info.json | cut -d '"' -f 2)
if [[ -z "$type" || -z "$name" || -z "$version" ]]; then
  echo "Error, missing type, name or version from info.json"
  exit 1
fi
targetSuffixPath="$type/$name/$version"

# production release
if [[ $* == *--production* ]]; then
  # making sure BACKBONE_ROOT is defined
  if [[ -z $BACKBONE_ROOT ]]; then
    echo "BACKBONE_ROOT is not defined!"
    exit 1
  fi

  if [[ "$BBASE_DEPLOYMENT_IGNORE_PROMPT" == "1" ]]; then
    response="yes"
  # showing a prompt confirmation to avoid mistakes
  else
    read -r -p "Are you sure you want to run the production release? [y/N] " response
  fi

  if [[ "$response" =~ ^(yes|y)$ ]]; then
    # running installation
    target=$(__normalizeOsPath "$BACKBONE_ROOT/$targetSuffixPath")
    if [[ -e "$target" ]]; then
      echo "Cannot override an existent production release: $target"
      exit 1
    fi

    # Since this config lives on the server, creating a build directory
    # on tmp for this module to speed-up things.
    buildDirectory=$(__normalizeOsPath "$(mktemp --tmpdir -d $name-build-production.XXXXXXXXX)")

    cmake -DCMAKE_INSTALL_PREFIX="$target" -B$buildDirectory
    cmake --install $buildDirectory --prefix="$target"

    echo "Production deployment completed: $target"
  fi
# development release
else

  # making sure BACKBONE_DEV_ROOT is defined
  if [[ -z $BACKBONE_DEV_ROOT ]]; then
    echo "BACKBONE_DEV_ROOT is not defined"
    exit 1
  fi

  # preparing build
  buildDirectory=$(__normalizeOsPath "$(mktemp --tmpdir -d $name-build-dev.XXXXXXXXX)")
  target=$(__normalizeOsPath "$BACKBONE_DEV_ROOT/$targetSuffixPath")

  # running installation
  cmake -DCMAKE_INSTALL_PREFIX="$target" -B$buildDirectory
  cmake --install $buildDirectory --prefix="$target"
fi
